---
title: "P0 - Informe"
output: html_notebook
---

## Tema N°1: Torneos de ESports

---------------

### Relevancia

ESports o electronic sports son competiciones de videojuegos que se han convertido en eventos de gran popularidad en Europa, Asia y Norte América, siendo en Latinoamérica estos eventos también cada vez más notorios y comunes.  
Es así que el siguiente estudio busca demostrar el crecimiento exponencial de estas competiciones y ofrecer información valiosa a organizaciones peruanas de ESports, medios de comunicación o cualquier entidad interesada. 

**¿Es el estudio de interés para la audiencia?**

Se define a la audiencia como la comunidad peruana organizadora de torneos de ESports. Y se considera de su interés el conocer:
- El crecimiento del mercado global de ESports en los últimos 20 años.
- La cantidad de ingresos obtenidos en cada torneo.
- Un conjunto de datos de los jugadores profesionales de ESports.
- Un conjunto de datos de los equipos profesionales de ESports.
- La cantidad de ingresos obtenidos por cada jugador de ESports.
- La cantidad de ingresos obtenidos por cada equipo de ESports.
- La cantidad de ingresos generados por cada videojuego en cada torneo.  

**¿Qué información se desea aportar al final del estudio?**  

En términos general se busca mostrar:

- El crecimiento exponencial del número de competiciones de ESport.
- El incentivo económico de participar en las competiciones.
- El interés actual de diferentes países latinoamericanos en ESport.
- La relevancia de cada videojuego para los eventos ESports y determinar cuál es el videojuego que conviene escoger para organizar una competencia en Perú.

---------------

### Proveniencia y disponibilidad de los datos
**¿Es posible llegar a la información que se propone de manera específica y concreta?**

Los datos serán recolectado de tres diferentes conjuntos de bases de datos:  

- [Top 100 Highest Overall Esport Team Earnings](https://www.kaggle.com/chanoncharuchinda/top-100-highest-overall-esport-team-earning?select=ESPORT+Team+Dataset)
  - Obtenida de https://www.kaggle.com con licencia CC0.
  - Data tomada de https://www.esportsearnings.com/teams/highest-overall.
  - Última actualización: 12 de septiembre del 2021.
- [eSports Earnings](https://www.kaggle.com/jackdaoud/esports-earnings-for-players-teams-by-game?select=country-and-continent-codes-list.csv)
  - Obtenida de https://www.kaggle.com con licencia CC0.
  - Data tomada de https://www.esportsearnings.com.
  - Última actualización: Enero 2021
- [Esports Earnings 1998 - 2021](https://www.kaggle.com/rankirsh/esports-earnings?select=HistoricalEsportData.csv)
  - Obtenida de https://www.kaggle.com con licencia CC0.
  - Data tomada de https://www.esportsearnings.com.
  - Última actualización: 30 de agosto del 2021.

Se analizarán datos como:

- Número de competiciones realizadas en cada país desde el año 1998.
- Número de competiciones realizadas por cada videojuego.
- Cantidad de ingresos generados en torneos por cada videojuego.
- Cantidad de ingresos generados por cada jugador profesional.
- Cantidad de ingresos generados por cada equipo profesional.


## Tema N°2: NBA Basketball

---------------

### Relevancia

Este estudio estadístico es de interés para medir la calidad de los jugadores de la NBA para otras ligas de Basketball como ACB, EBA, LEB Oro mejoren su calidad deportiva 

**¿Es el estudio de interés para la audiencia?**

Se define a la audiencia como la comunidad peruana organizadora de torneos de ESports. Y se considera de su interés el conocer:
- El crecimiento del mercado global de ESports en los últimos 20 años.
- La cantidad de ingresos obtenidos en cada torneo.
- Un conjunto de datos de los jugadores profesionales de ESports.
- Un conjunto de datos de los equipos profesionales de ESports.
- La cantidad de ingresos obtenidos por cada jugador de ESports.
- La cantidad de ingresos obtenidos por cada equipo de ESports.
- La cantidad de ingresos generados por cada videojuego en cada torneo.  

**¿Qué información se desea aportar al final del estudio?**  

Mostrar los factores que convierten a la NBA sea la liga más competitiva de baloncesto además analizar las características de cada jugador y predecir la trayectoria las mejores estrellas de este deporte.

En términos general se busca mostrar:

- El crecimiento exponencial del número de competiciones de ESport.
- El incentivo económico de participar en las competiciones.
- El interés actual de diferentes países latinoamericanos en ESport.
- La relevancia de cada videojuego para los eventos ESports y determinar cuál es el videojuego que conviene escoger para organizar una competencia en Perú.

---------------

### Proveniencia y disponibilidad de los datos
**¿Es posible llegar a la información que se propone de manera específica y concreta?**

Los datos serán recolectados de la siguiente base de datos:  

- [Basketball Dataset](https://www.kaggle.com/wyattowalsh/basketball)
  - Obtenida de https://www.kaggle.com con licencia CC BY-SA 4.0.
  - Data tomada de https://www.nba.com/stats/.
  - Última actualización: 15 de septiembre del 2021.

Se analizarán datos como:

- Juegos en los que participaron en una temporada cada equipo.
- Los nombres, equipos y juegos en los cuales un jugador participó y no participó.
- Salario de cada jugador y tipo de contrato.
- Salario de cada equipo.
- Fundador, estadio, año de fundación y ciudad de cada equipo.


## Tema N°3: ¿Cómo afecta el consumo de frutos secos en la alimentación de los alumnos de UTEC?

---------------

### Relevancia

La alimentación es un pilar importante para los estudiantes, ya que estar bien alimentados significa tener la energía suficiente para cumplir con tu rutina diaria de clases, además de beneficiar la salud de los mismos. Por ese motivo, el consumo de frutos secos es altamente recomendable en las dietas de los estudiantes, ya que se sabe que disminuyen los niveles de colesterol, disminuye el riesgo de diabetes tipo 2 y es altamente saciante. Además, ayuda a prevenir la obesidad, así como, reduce el consumo de alimentos procesados. Conocer como afecta el consumo de estos frutos en los estudiantes conociendo sus hábitos alimenticios es nuestro objetivo principal. 

### Proveniencia y disponibilidad de los datos

Los datos serán aportados por los estudiantes de UTEC dispuestos a aportar a este estudio. 

Los datos a tomar en cuenta serán: 
- Talla
- Peso
- Edad
- Ciclo 
- Género
- Hábitos alimenticios 
- Frecuencia de consumo de frutos secos
- Cantidad de consumo de frutos secos
- Tipos de frutos secos que consumen

**¿Es el estudio de interés para la audiencia?**

Sí, porque al mostrar como influye de manera positiva los frutos secos en la alimentación de los estudiantes, no solo mejoraría directamente su salud mediante el mejoramiento de hábitos alimenticios, sino que indirectamente mejorarían en el aspecto académico, ya que una mejor alimentación, significa más energía y un mejor estado de ánimo para desarrollar nuestras actividades. 

**¿Qué información se desea aportar al final del estudio?**  

La información recolectada mediante encuestas, de forma cuantitativa, cómo afecta el consumo de frutos secos en el bienestar de los estudiantes. 

**¿Es posible llegar a la información que se propone de manera específica  y concreta?**

Va a depender de la veracidad de las respuestas en la encuesta, aún así, no se puede obtener una información 100% exacta, debido a los márgenes de error que están presentes en los estudios estadísticos. En caso obtengamos respuestas totalmente verídicas, se podría decir que la información será específica y concreta.
